# Generated by Django 4.2.3 on 2023-07-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fontpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontpayer', models.CharField(max_length=150)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='monthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthYear', models.CharField(max_length=150)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlogin', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=150)),
                ('recipedate', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('MonthYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.monthyear')),
                ('fontpayer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.fontpayer')),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='paytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytype', models.CharField(max_length=150)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
        migrations.AddField(
            model_name='monthyear',
            name='userlogin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin'),
        ),
        migrations.AddField(
            model_name='fontpayer',
            name='userlogin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin'),
        ),
        migrations.CreateModel(
            name='expensetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensetype', models.CharField(max_length=150)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=150)),
                ('paydate', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('MonthYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.monthyear')),
                ('category_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category')),
                ('expensetype_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.expensetype')),
                ('paytype_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.paytype')),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='credity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credity', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('MonthYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.monthyear')),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='userlogin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin'),
        ),
        migrations.CreateModel(
            name='buylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('buylist', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valortotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('MonthYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.monthyear')),
            ],
        ),
        migrations.CreateModel(
            name='aporty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporty', models.CharField(max_length=150)),
                ('Ativo', models.CharField(max_length=10)),
                ('Bank_Brok', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('Create_Data', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('MonthYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.monthyear')),
                ('userlogin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.userlogin')),
            ],
        ),
    ]
