# Generated by Django 4.2.3 on 2023-07-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aporty',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='credity',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='fontpayer',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='monthyear',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='paytype',
            name='userlogin_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='userlogin_id',
        ),
        migrations.DeleteModel(
            name='userlogin',
        ),
    ]
